#ifndef __CAT_VS_DOG_MODEL_DATA_H__
#define __CAT_VS_DOG_MODEL_DATA_H__

//this file is generated by tflite2c.py
constexpr int kNumCols = 96;
constexpr int kNumRows = 96;
constexpr int kNumChannels = 3;

constexpr int kMaxImageSize = kNumCols * kNumRows * kNumChannels;

extern const unsigned char g_cat_vs_dog_model_data[];
extern const unsigned int g_cat_vs_dog_model_data_len;
extern const char* g_cat_vs_dog_model_classes[];
extern const unsigned int g_cat_vs_dog_model_classes_num;

#endif
